import json,os
D=[("KL-01","Thiruvananthapuram","Thiruvananthapuram"),("KL-02","Kollam","Kollam"),("KL-03","Pathanamthitta","Pathanamthitta"),("KL-04","Alappuzha","Alappuzha"),("KL-05","Kottayam","Kottayam"),("KL-06","Idukki","Painavu"),("KL-07","Ernakulam","Ernakulam"),("KL-08","Thrissur","Thrissur"),("KL-09","Palakkad","Palakkad"),("KL-10","Malappuram","Malappuram"),("KL-11","Kozhikode","Kozhikode"),("KL-12","Wayanad","Kalpetta"),("KL-13","Kannur","Kannur"),("KL-14","Kasaragod","Kasaragod")]
P="https://parivahan.gov.in/"
# id,name,group,online,steps,docs,fee lines
S=[("learners-licence","Learner's Licence","Licence","Online + test at RTO","Apply for the learner's licence on Parivahan|Upload documents and pay the fee online|Book a test slot|Attend the computer-based rules test at your RTO|Download the learner's licence after passing","Age proof|Address proof|Passport-size photo|Signature|Medical self-declaration (Form 1)",["Application fee","Test fee"]),
("dl-renewal","Driving Licence Renewal","Licence","Online + RTO visit if required","Log in to Parivahan and choose Driving Licence Services|Enter your DL number and date of birth|Fill Form 9 and upload documents|Pay the fee online|Book a slot if the portal asks for a visit","Existing driving licence|Address proof|Passport-size photo|Form 9|Medical certificate (Form 1A) where applicable",["Renewal fee","Service charge"]),
("duplicate-dl","Duplicate Driving Licence","Licence","Mostly online","Log in to Parivahan and choose duplicate DL|File an FIR or written declaration only if required|Fill Form 2 and upload documents|Pay the fee online|Track the card by post","ID and address proof|Passport-size photo|Form 2|Copy of lost licence if you have one",["Duplicate fee"]),
("ownership-transfer","Vehicle Ownership Transfer","Vehicle","Online + RTO visit","Seller and buyer both sign Form 29 and 30|Buyer applies on Parivahan|Upload RC, insurance, PUC and ID proofs|Pay the fee online|Visit the RTO if inspection or verification is asked","Original RC|Form 29 and Form 30|Valid insurance|PUC certificate|Buyer ID and address proof|NOC if the vehicle is financed",["Transfer fee","Service charge"]),
("duplicate-rc","Duplicate RC","Vehicle","Online","Log in to Parivahan and choose RC services|Select duplicate RC|Upload documents and pay online|Track the smart card status","Vehicle number and chassis details|Owner ID proof|Address proof|FIR copy if RC is lost",["Duplicate RC fee"]),
("fitness-certificate","Fitness Certificate","Vehicle","Online booking + inspection","Book an inspection slot on Parivahan|Pay the fee online|Bring the vehicle to the RTO or test centre|Pass the inspection|Download the certificate","RC|Insurance|PUC certificate|Previous fitness certificate",["Fitness fee","Inspection charge"]),
("address-change","Address Change on DL or RC","Other","Online","Log in to Parivahan|Select change of address|Upload new address proof|Pay the fee online|Receive the updated card by post","Existing DL or RC|New address proof|Passport-size photo",["Address change fee"]),
("pay-echallan","Traffic e-Challan Payment","Other","Online","Open the e-challan service on Parivahan|Enter challan, vehicle or DL number|Check the challan details carefully|Pay online|Save the receipt","Challan, vehicle or DL number|Payment method",["Challan amount as issued"])]
S+=[("green-tax","Green Tax Payment","Vehicle","Online","Open the taxation service on Parivahan or the Kerala MVD site|Enter your vehicle number|Check any arrears shown|Pay online|Save the receipt","Vehicle registration number|RC details|Payment method",["Green tax"]),
("hsrp","High Security Number Plate (HSRP)","Vehicle","Online booking","Enter registration details on the official HSRP booking site or the Duplicate HSRP service on Vahan|Choose home fitment or a dealership where offered|Select a nearby dealership|Pay online and keep the acknowledgement","Registration number and chassis details|RC|Mobile number for the acknowledgement",["HSRP fee"]),
("choice-number","Choice Number Booking","Other","Online (fancy number portal)","Open the Parivahan fancy number portal|Check whether your preferred number is available|Book, or register for the e-auction where the number is auctioned|Pay within the stated time|Use the number when you register the vehicle","Aadhaar-linked details (individuals)|Vehicle or dealer details|Payment method",["Choice number fee"])]
FEES={s[0]:[(f,None,None) for f in s[6]] for s in S}  # (label, OFFICIAL fee, REPORTED fee). Official fees from Tanmay's verified dataset (CMVR schedules, Kerala Finance Act)
FEES["learners-licence"]=[("Application fee",150,None),("Test fee",50,None),("Learner renewal, if needed",None,300),("Re-test, if needed",None,600)]
FEES["dl-renewal"]=[("Renewal fee, within grace period",200,None),("Smart card charge, applicants report",None,200)]
FEES["duplicate-dl"]=[("Total including stamp paper, e-treasury and notary items",None,1750),("PVC card update with detail changes",None,1025)]
FEES["ownership-transfer"]=[("Transfer fee, car or LMV non-transport",300,None),("Transfer fee, two-wheeler",150,None),("Smart card charge",200,None),("All-in via Akshaya centre, applicants report",None,750)]
FEES["duplicate-rc"]=[("Duplicate RC fee, car or LMV",300,None),("Duplicate RC fee, two-wheeler",150,None)]
FEES["address-change"]=[("Address change fee",200,None)]
FEES["green-tax"]=[("Green tax, private 4+ wheeler over 15 years, per 5 years",400,None)]
FEES["choice-number"]=[("Choice number fee, unlisted number",5000,None),("Choice number fee, applicants report",None,3000)]
DOCS={"learners-licence":"Age proof (10th certificate)|Aadhaar|Address proof|Eye-test certificate|Passport-size photos"}
DD={"Address proof":"Accepted examples: passport, voter ID, Aadhaar, electricity or telephone bill, bank passbook, registered rent agreement.","New address proof":"Accepted examples: passport, voter ID, Aadhaar, electricity or telephone bill (from the last 3 months), bank passbook, registered rent agreement.","Age proof (10th certificate)":"Accepted examples: birth certificate, 10th class certificate, passport, PAN card.","ID and address proof":"ID: Aadhaar, passport, voter ID, PAN card, driving licence. Address: passport, voter ID, Aadhaar, electricity or telephone bill, bank passbook, registered rent agreement.","Owner ID proof":"Accepted examples: Aadhaar, passport, voter ID, PAN card, driving licence.","Buyer ID and address proof":"ID: Aadhaar, passport, voter ID, PAN card, driving licence. Address: passport, voter ID, Aadhaar, electricity or telephone bill, bank passbook, registered rent agreement.","Passport-size photo":"Recent photo with a plain white background, as per the portal's upload rules.","Passport-size photos":"Recent photos with a plain white background, as per the portal's upload rules."}
TIME={"dl-renewal":"Applicants report about 1 to 2 weeks for approval, with the physical card arriving later","duplicate-dl":"Applicants report 3 to 4 days for approval; card delivery can take longer"}
NOTE={"learners-licence":"Applicants report a 20-question test needing 12 correct answers, but the format can vary. Practise with the Parivahan question bank. Originals and copies may both be asked for.","duplicate-dl":"Some applicants add a small printing charge at an RTO e-Seva counter to get the PDF licence on a PVC card.","green-tax":"A published Kerala Finance Act schedule cites Rs 400 per 5 years for private four-wheelers over 15 years. Confirm the current rate before paying.","hsrp":"Availability for older vehicles has varied. Check the portal before you travel, and keep the dealer acknowledgement.","choice-number":"Some numbers are auctioned and some are booked directly. Complete payment inside the stated window."}
def ft(o,r):return ("Official fee: to be confirmed on parivahan.gov.in" if o is None else f"Official fee: Rs {o}")+(f" (some applicants report ~Rs {r} - amounts may vary and change without notice)" if r else " (amounts may change without notice)")
data={"note":"FEES: verify against parivahan.gov.in before launch. null = not yet verified, never guess.","link":P,
"services":{s[0]:{"name":s[1],"group":s[2],"online":s[3],"time":TIME.get(s[0]),"note":NOTE.get(s[0]),"steps":s[4].split("|"),"docs":DOCS.get(s[0],s[5]).split("|"),"fees":[{"l":a,"official":o,"reported":r} for a,o,r in FEES[s[0]]]} for s in S},
"districts":[{"code":c,"district":d,"town":t} for c,d,t in D],"docdetail":DD}
JS="""// DATASET. FEES MARKED null ARE UNVERIFIED. Fill each from parivahan.gov.in before launch.
const KT=%s;
const $=s=>document.querySelector(s),ic=(p)=>`<svg class="i" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${p}</svg>`;
const feeTxt=f=>(f.official==null?'Official fee: to be confirmed on parivahan.gov.in':`Official fee: \u20b9${f.official}`)+(f.reported?` (some applicants report ~\u20b9${f.reported} - amounts may vary and change without notice)`:' (amounts may change without notice)');
function tick(root){root.querySelectorAll('input[data-k]').forEach(b=>{try{b.checked=localStorage.getItem(b.dataset.k)==='1'}catch(e){}b.onchange=()=>{try{localStorage.setItem(b.dataset.k,b.checked?'1':'0')}catch(e){}prog(root)}});prog(root)}
function prog(r){const a=[...r.querySelectorAll('input[data-k]')],n=a.filter(x=>x.checked).length,p=r.querySelector('.prog');if(p)p.textContent=n+' of '+a.length+' documents ready'}
function docHtml(sid,i,x){const d=KT.docdetail[x];if(!d)return `<label class="chk"><input type="checkbox" data-k="kt:${sid}:${i}"> ${x}</label>`;return `<div class="doc"><label class="chk"><input type="checkbox" data-k="kt:${sid}:${i}"> ${x}</label><button type="button" class="docbtn" aria-expanded="false" aria-label="Show accepted documents">\u25be</button><div class="docd" hidden>${d}</div></div>`}
document.addEventListener('click',e=>{const b=e.target.closest('.docbtn');if(!b)return;const d=b.parentElement.querySelector('.docd'),open=d.hidden;d.hidden=!open;b.setAttribute('aria-expanded',String(open));b.textContent=open?'\u25b4':'\u25be'});
function render(sid,did){const s=KT.services[sid],d=KT.districts[did],o=$('#out');if(!s||!d){o.innerHTML='<p class="note">Pick a service and a district first.</p>';return}
const tot=s.fees.every(f=>f.official!=null)?'\u20b9'+s.fees.reduce((a,f)=>a+f.official,0):'To be confirmed';
o.innerHTML=`<div class="grid g2"><div class="card" id="cl"><span class="badge">${s.online}</span><h3>${s.name}: your checklist</h3><p class="prog"></p>
${s.docs.map((x,i)=>docHtml(sid,i,x)).join('')}
<p class="wm">keralamtransport.com - verify on parivahan.gov.in</p></div>
<div class="card"><h3>Steps</h3><ol class="steps">${s.steps.map(x=>`<li>${x}</li>`).join('')}</ol>${s.note?`<p class="note">${s.note}</p>`:''}<p class="note">Time estimate: ${s.time||'to be confirmed; it depends on your RTO and slot availability'}.</p></div></div>
<div class="grid g2"><div class="card"><h3>Fees</h3><table>${s.fees.map(f=>`<tr><td>${f.l}</td><td>${feeTxt(f)}</td></tr>`).join('')}<tr><th>Total</th><th>${tot}</th></tr></table><p class="note">Any gap between official and reported amounts is usually a service charge or an optional add-on. Always ask for a receipt.</p></div>
<div class="card"><h3>${d.district} RTO</h3><p><strong>${d.code}</strong> - ${d.town}</p><p class="note">Address and hours: confirm on the office page before you travel.</p><a class="btn" href="/rto-offices/${d.code.toLowerCase()}.html">Office details</a></div></div>
<div class="row"><a class="btn amb" href="${KT.link}" target="_blank" rel="noopener">Start on Parivahan</a><button class="btn ghost" id="shot">Take Screenshot</button></div>`;
tick(o);$('#shot').onclick=()=>{const l=document.createElement('script');const go=()=>htmlToImage.toPng($('#cl'),{backgroundColor:'#F6F1E4'}).then(u=>{const a=document.createElement('a');a.href=u;a.download='checklist-'+sid+'.png';a.click()});if(window.htmlToImage)go();else{l.src='https://cdn.jsdelivr.net/npm/html-to-image@1.11.11/dist/html-to-image.js';l.onload=go;document.head.appendChild(l)}}}
function init(){const f=$('#finder');if(!f)return;const sv=f.querySelector('[name=s]'),dv=f.querySelector('[name=d]');
f.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{f.querySelectorAll('.chip').forEach(x=>x.setAttribute('aria-pressed','false'));c.setAttribute('aria-pressed','true');sv.value=c.dataset.s});
f.onsubmit=e=>{e.preventDefault();render(sv.value,dv.value);$('#out').scrollIntoView({behavior:'smooth'})};
const p=f.dataset.s;if(p){f.querySelectorAll('.chip').forEach(c=>c.setAttribute('aria-pressed',c.dataset.s===p))}
document.querySelectorAll('.static').forEach(tick)}
document.addEventListener('DOMContentLoaded',init);"""%json.dumps(data)
CSS=""":root{--t:#0C5B4C;--a:#E8962E;--sand:#F6F1E4;--ink:#1C2B26;--line:#DDD5BF}*{box-sizing:border-box}body{margin:0;background:var(--sand);color:var(--ink);font:16px/1.6 'Plus Jakarta Sans',sans-serif;padding-bottom:64px}
h1,h2,h3{font-family:Fraunces,serif;line-height:1.2;margin:.2em 0 .5em}h1{font-size:2rem}h2{font-size:1.5rem}a{color:var(--t)}.w{max-width:1040px;margin:auto;padding:0 18px}
header{background:#fff;border-bottom:1px solid var(--line)}header .w{display:flex;justify-content:space-between;align-items:center;padding:12px 18px;flex-wrap:wrap;gap:8px}.logo{font:700 1.2rem Fraunces,serif;text-decoration:none;display:flex;gap:8px;align-items:center}nav a{margin-right:14px;font-size:.9rem;text-decoration:none}
.hero{position:relative;overflow:hidden;background:var(--t);color:#fff;padding:36px 0 40px}.hero:before{content:"കേരളം";position:absolute;right:-10px;top:-10px;font-size:9rem;opacity:.07;line-height:1;pointer-events:none}.hero .w{position:relative}
.sec{padding:36px 0}.c{text-align:center}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:18px}.grid{display:grid;gap:14px;margin:14px 0}.g2{grid-template-columns:1fr}.g3,.g4{grid-template-columns:1fr}
@media(min-width:700px){.g2{grid-template-columns:1fr 1fr}.g3{grid-template-columns:repeat(3,1fr)}.g4{grid-template-columns:repeat(4,1fr)}.s2{grid-template-columns:2fr 1fr}body{padding-bottom:0}.bar{display:none}h1{font-size:2.6rem}}
.btn{display:inline-block;border:0;border-radius:8px;padding:12px 18px;background:var(--t);color:#fff;font:600 1rem inherit;font-family:inherit;text-decoration:none;cursor:pointer}.amb{background:var(--a);color:var(--ink)}.ghost{background:#fff;color:var(--t);border:1px solid var(--t)}
.fm{background:#fff;color:var(--ink);border-radius:16px;padding:16px;margin-top:18px}.fm h3{font-size:1rem;font-family:'Plus Jakarta Sans';margin:.8em 0 .4em}.chip{border:1px solid var(--line);background:var(--sand);border-radius:8px;padding:8px 12px;margin:0 6px 6px 0;cursor:pointer;font:inherit}.chip[aria-pressed=true]{background:var(--t);color:#fff;border-color:var(--t)}
select{width:100%;padding:11px;border-radius:8px;border:1px solid var(--line);font:inherit;margin-bottom:12px}.strip{background:#fff;border-bottom:1px solid var(--line);padding:12px 0;font-size:.9rem}.strip .w{display:flex;gap:18px;flex-wrap:wrap;justify-content:center}
.i{width:18px;height:18px;vertical-align:-3px;margin-right:6px}.badge{display:inline-block;background:#E4EFEA;color:var(--t);border-radius:8px;padding:2px 10px;font-size:.8rem;font-weight:600}.badge.ex{background:#FBE9CF}
.chk{display:block;padding:6px 0;border-bottom:1px dashed var(--line)}.chk input{margin-right:8px;accent-color:var(--t)}
.doc{position:relative;border-bottom:1px dashed var(--line)}.doc .chk{border:0;padding-right:38px}.docbtn{position:absolute;right:2px;top:6px;width:28px;height:28px;border:1px solid var(--line);background:var(--sand);border-radius:6px;cursor:pointer;font:inherit;color:var(--t);line-height:1}.docd{font-size:.88rem;opacity:.85;padding:0 0 10px 26px}.steps li{margin-bottom:8px}table{width:100%;border-collapse:collapse;font-size:.92rem}td,th{text-align:left;padding:8px 4px;border-bottom:1px solid var(--line);vertical-align:top}.note,.wm{font-size:.85rem;opacity:.75}.row{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}
details{background:#fff;border:1px solid var(--line);border-radius:12px;padding:12px 16px;margin-bottom:8px}summary{font-weight:600;cursor:pointer}footer{background:var(--ink);color:#dfe8e3;padding:28px 0;font-size:.9rem}footer a{color:#fff;margin-right:12px}
.bar{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:1px solid var(--line);padding:10px 14px;z-index:9}.bar .btn{display:block;text-align:center}.small a{text-decoration:none}"""
IC={"c":'<path d="M20 6 9 17l-5-5"/>',"m":'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',"f":'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/>'}
def ic(k):return f'<svg class="i" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{IC[k]}</svg>'
def docitem(kp,i,x):
    d=DD.get(x)
    if d:return f'<div class="doc"><label class="chk"><input type="checkbox" data-k="{kp}:{i}"> {x}</label><button type="button" class="docbtn" aria-expanded="false" aria-label="Show accepted documents">\u25be</button><div class="docd" hidden>{d}</div></div>'
    return f'<label class="chk"><input type="checkbox" data-k="{kp}:{i}"> {x}</label>'
FAV='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="7" fill="#0C5B4C"/><rect x="5" y="10" width="22" height="12" rx="2.5" fill="#ffffff"/><path d="M5 12.5a2.5 2.5 0 0 1 2.5-2.5h17A2.5 2.5 0 0 1 27 12.5V14H5z" fill="#1E5AA8"/><text x="16" y="20.6" font-family="Arial,sans-serif" font-size="6.5" font-weight="bold" fill="#000000" text-anchor="middle">KL 07</text></svg>'
def page(path,title,desc,body,ld=""):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><link rel="canonical" href="https://keralamtransport.com{path}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:type" content="website"><meta property="og:url" content="https://keralamtransport.com{path}"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Fraunces:wght@600;700&family=Plus+Jakarta+Sans:wght@400;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css">{ld}</head><body><header><div class="w"><a class="logo" href="/"><img src="/favicon.svg" width="26" height="26" alt="">Keralam Transport</a><nav><a href="/finder.html">Finder</a><a href="/#services">Services</a><a href="/#offices">RTO offices</a><a href="/blog/index.html">Blog</a><a href="/about.html">About</a></nav></div></header>{body}<footer><div class="w"><p><a href="/about.html">About</a><a href="/contact.html">Contact</a><a href="/privacy.html">Privacy</a><a href="/disclaimer.html">Disclaimer and Terms</a></p><p>Not affiliated with Kerala MVD - verify on <a href="https://parivahan.gov.in/" rel="noopener">parivahan.gov.in</a>. Fees and rules change without notice.</p></div></footer><div class="bar"><a class="btn amb" href="/finder.html">Show my process</a></div><script src="/finder.js" defer></script></body></html>'''
def form(pre=None):
    ch="".join(f'<h3>{g}</h3>'+"".join(f'<button type="button" class="chip" data-s="{s[0]}" aria-pressed="false">{s[1]}</button>' for s in S if s[2]==g) for g in ["Licence","Vehicle","Other"])
    opts="".join(f'<option value="{i}">{d[1]} ({d[0]})</option>' for i,d in enumerate(D))
    return f'<form id="finder" class="fm" data-s="{pre or ""}"><input type="hidden" name="s" value="{pre or ""}">{ch}<h3>Your district</h3><select name="d">{opts}</select><button class="btn amb" type="submit">Show my process</button></form><div id="out"></div>'
def faq(qs):return "".join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in qs),'<script type="application/ld+json">'+json.dumps({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in qs]})+'</script>'
F=[("Are the fees on this site final?","No. Each fee is shown as the official amount from Parivahan, and amounts change without notice. Where a fee is not yet confirmed we say so instead of guessing."),("Is Keralam Transport a government site?","No. It is an independent guide and is not affiliated with Kerala MVD. Every application is filed on parivahan.gov.in."),("How hard is the Kerala driving test?","Kerala's driving test is India's toughest by reputation, and the ground test rewards practice. Book enough lessons before your slot."),("Do I need to visit the RTO?","Many steps are online, but some services still need an in-person visit for a test or verification. Each service page shows an online or offline badge.")]
def w(p,c):
    os.makedirs(os.path.dirname("."+p) or ".",exist_ok=True);open("."+p,"w").write(c)
w("/favicon.svg",FAV);w("/finder.js",JS);w("/style.css",CSS)
fq,fl=faq(F)
cards="".join(f'<a class="card small" href="/services/{s[0]}.html"><span class="badge">{s[3]}</span><h3>{s[1]}</h3><p class="note">Fee: verify on Parivahan. Time: varies by RTO.</p></a>' for s in S)
offs="".join(f'<a class="card small" href="/rto-offices/{c.lower()}.html"><strong>{c}</strong><br>{d} RTO<br><span class="note">{t}</span></a>' for c,d,t in D)
sample=S[1]
home=f'''<section class="hero"><div class="w"><h1>Kerala RTO services, explained step by step</h1><p>Pick a service and your district. Get the steps, the documents to gather and the fee to expect, before you leave home.</p>{form()}</div></section>
<div class="strip"><div class="w"><span>{ic("c")}11 services explained</span><span>{ic("m")}All 14 RTO offices</span><span>{ic("f")}Free checklists</span></div></div>
<section class="sec" id="services"><div class="w"><h2>Popular services, with fee and time on each card</h2><div class="grid g3">{cards}</div></div></section>
<section class="sec"><div class="w"><span class="badge ex">Example</span><h2>What a driving licence renewal checklist looks like</h2><div class="card static">{"".join(docitem("kt:sample",i,x) for i,x in enumerate(sample[5].split("|")))}<p class="prog note"></p></div></div></section>
<section class="sec" id="offices"><div class="w"><h2>All 14 Kerala RTO offices, KL-01 to KL-14</h2><div class="grid g4">{offs}</div></div></section>
<section class="sec c"><div class="w"><h2>How it works in four steps</h2><div class="grid g4"><div class="card"><strong>1</strong><br>Choose your service</div><div class="card"><strong>2</strong><br>Choose your district</div><div class="card"><strong>3</strong><br>Tick off documents</div><div class="card"><strong>4</strong><br>Finish on Parivahan</div></div></div></section>
<section class="sec"><div class="w"><h2>Questions people ask before applying</h2>{fq}</div></section>'''
w("/index.html",page("/","Keralam Transport: Kerala RTO services, steps, documents and fees","Free Kerala RTO service finder. Steps, document checklists and fees for licence, vehicle and other services in all 14 districts.",home,fl))
w("/finder.html",page("/finder.html","RTO Service Finder for Kerala: steps, documents, fees","Choose a service and district to get your Kerala RTO process, checklist and fee table.",f'<section class="sec"><div class="w"><h1>Kerala RTO Service Finder</h1>{form()}</div></section>'))
for s in S:
    id,n,g,on,st,dc,fe=s;rel="".join(f'<a href="/services/{x[0]}.html">{x[1]}</a><br>' for x in S if x[0]!=id and x[2]==g) or '<a href="/finder.html">Try the finder</a>'
    q,l=faq([(f"What is the fee for {n} in Kerala?","The official fee is listed on Parivahan and changes without notice. Check it there before you pay."),(f"Can I do {n} online?",f"{on}. Confirm on Parivahan for your case.")])
    b=f'''<section class="sec"><div class="w"><h1>{n} in Kerala</h1><div class="card"><span class="badge">{on}</span><p><strong>Fee:</strong> see the fee table below. <strong>Time:</strong> {TIME.get(id) or "varies by RTO"}.</p>{("<p class=note>"+NOTE[id]+"</p>") if id in NOTE else ""}</div>{form(id)}<div class="grid g2"><div class="card"><h2>Steps</h2><ol class="steps">{"".join(f"<li>{x}</li>" for x in st.split("|"))}</ol></div><div class="card static"><h2>Documents</h2>{"".join(docitem("kt:"+id,i,x) for i,x in enumerate(dc.split("|")))}<p class="prog note"></p></div></div>
<div class="card"><h2>Fee table</h2><table>{"".join(f"<tr><td>{a}</td><td>{ft(o,r)}</td></tr>" for a,o,r in FEES[id])}</table></div><h2>Common mistakes that get applications rejected</h2><ul><li>Name or date of birth spelled differently across documents.</li><li>Blurred or expired uploads.</li><li>Paying before checking the details on screen.</li></ul>{q}<h2>Related</h2><p>{rel}</p></div></section>'''
    w(f"/services/{id}.html",page(f"/services/{id}.html",f"{n} in Kerala: steps, documents, fees",f"How to do {n} in Kerala: steps, document checklist and fee table.",b,l))
for c,d,t in D:
    b=f'<section class="sec"><div class="w"><h1>{d} RTO ({c})</h1><div class="card"><p><strong>Town:</strong> {t}<br><strong>Address and hours:</strong> to be confirmed on parivahan.gov.in.<br><strong>Jurisdiction:</strong> {d} district.</p></div><h2>Services</h2><p>'+"".join(f'<a href="/services/{s[0]}.html">{s[1]}</a><br>' for s in S)+f'</p><div class="card"><iframe title="Map" loading="lazy" width="100%" height="260" style="border:0" src="https://www.google.com/maps?q={t}+RTO+Kerala&output=embed"></iframe></div></div></section>'
    w(f"/rto-offices/{c.lower()}.html",page(f"/rto-offices/{c.lower()}.html",f"{d} RTO ({c}): services and details",f"{d} RTO office, KL code {c}: jurisdiction and services.",b))
T={"about":("About Keralam Transport","An independent, plain-language guide to Kerala RTO services. We report official processes and fees only."),"contact":("Contact","Keralam Transport is a free, self-serve guide with no support inbox or phone line. If you spot an error, check the current rule on parivahan.gov.in, which is the source this site follows."),"privacy":("Privacy","This site has no accounts. Checklist progress stays in your own browser storage and is never sent to us."),"disclaimer":("Disclaimer and Terms","Not affiliated with Kerala MVD. Information is general guidance. Verify all fees and rules on parivahan.gov.in.")}
for k,(h,t) in T.items():w(f"/{k}.html",page(f"/{k}.html",f"{h} | Keralam Transport",t,f'<section class="sec"><div class="w"><h1>{h}</h1><p>{t}</p></div></section>'))

POSTS=[("kerala-driving-test-what-to-expect","Kerala driving test: what to expect and how to prepare","Applicants describe a three-part test: an 8 course, the H test and a road test. Kerala's driving test is India's toughest by reputation, so plan for more than one attempt.",
"""<section class="sec"><div class="w"><h1>Kerala driving test: what to expect and how to prepare</h1><p>Applicants describe a test with three parts: the 8, the H, and a road test. The rules changed in 2024 and people say the new course feels different from the old H-only test. Kerala's driving test is India's toughest by reputation. Be honest about your practice hours.</p><h2>Practise on the real ground if you can</h2><p>One applicant who failed the H test three times said the test ground differed from their practice ground, then passed later. Others say the reference rods still exist on the ground, so learn to judge distance from the driver's seat instead of relying on one marker.</p><h2>Slots fill fast</h2><p>Applicants say booking opens in the morning, around 9 or 10 a.m., and slots can be full within minutes. Some report waits of several months. Keep your learner's licence valid while you wait, and budget for a renewal. Fees for that are on our <a href="/services/learners-licence.html">learner's licence page</a>.</p><h2>Driving school or self-service?</h2><p>Many applicants get the learner's licence themselves online and use a driving school for practice. Others use a school because it helps with slot booking. A school's price can include lessons, test-day support and add-ons, so ask for an itemised quote.</p><p class="note">Based on what applicants report. Rules and slots change. Check parivahan.gov.in.</p></div></section>""")]
for _s,_t,_d,_b in POSTS:
    w("/blog/"+_s+".html",page("/blog/"+_s+".html",_t+" | Keralam Transport",_d,_b))
w("/blog/index.html",page("/blog/index.html","Blog | Keralam Transport","Plain guides to Kerala RTO processes.",'<section class="sec"><div class="w"><h1>Blog</h1>'+"".join(f'<a class="card small" style="display:block;margin-bottom:12px" href="/blog/{_s}.html"><h3>{_t}</h3><p class="note">{_d}</p></a>' for _s,_t,_d,_b in reversed(POSTS))+'</div></section>'))
urls=["/blog/index.html"]+[f"/blog/{_s}.html" for _s,_,_,_ in POSTS]+["/","/finder.html"]+[f"/services/{s[0]}.html" for s in S]+[f"/rto-offices/{c.lower()}.html" for c,_,_ in D]+[f"/{k}.html" for k in T]
w("/sitemap.xml",'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+"".join(f"<url><loc>https://keralamtransport.com{u}</loc></url>" for u in urls)+"</urlset>")
w("/robots.txt","User-agent: *\nAllow: /\nSitemap: https://keralamtransport.com/sitemap.xml\n")
print(len(urls))
